//! The shared webhook vectors (`tests/fixtures/webhooks.json`, generated by the conformance
//! suite of lettermint/sdk-generator).

use std::collections::{BTreeMap, HashMap};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use base64::Engine as _;
use lettermint::{Webhook, WebhookVerificationReason};
use serde_json::Value;

fn vectors() -> Vec<Value> {
    let file: Value = serde_json::from_str(include_str!("fixtures/webhooks.json")).unwrap();
    file["vectors"].as_array().unwrap().clone()
}

fn reason(code: &str) -> Option<WebhookVerificationReason> {
    use WebhookVerificationReason::*;
    Some(match code {
        "valid" => return None,
        "signature_header_missing" => SignatureHeaderMissing,
        "signature_header_malformed" => SignatureHeaderMalformed,
        "delivery_header_missing" => DeliveryHeaderMissing,
        "delivery_timestamp_mismatch" => DeliveryTimestampMismatch,
        "timestamp_out_of_tolerance" => TimestampOutOfTolerance,
        "signature_mismatch" => SignatureMismatch,
        other => panic!("unknown reason {other}"),
    })
}

#[test]
fn every_vector_verifies_as_expected() {
    let vectors = vectors();
    assert!(vectors.len() >= 25);
    for vector in vectors {
        let id = vector["id"].as_str().unwrap();
        let body = base64::engine::general_purpose::STANDARD
            .decode(vector["body_base64"].as_str().unwrap())
            .unwrap();
        let now = UNIX_EPOCH + Duration::from_secs(vector["now"].as_u64().unwrap());
        let webhook = Webhook::new(vector["secret"].as_str().unwrap())
            .unwrap()
            .with_tolerance(Duration::from_secs(vector["tolerance"].as_u64().unwrap()));
        let pairs: BTreeMap<String, String> = vector["headers"]
            .as_object()
            .unwrap()
            .iter()
            .map(|(name, value)| (name.clone(), value.as_str().unwrap().to_owned()))
            .collect();
        let hash: HashMap<&str, &str> = pairs
            .iter()
            .map(|(k, v)| (k.as_str(), v.as_str()))
            .collect();
        let mut header_map = http::HeaderMap::new();
        for (name, value) in &pairs {
            header_map.append(
                http::HeaderName::from_bytes(name.as_bytes()).unwrap(),
                http::HeaderValue::from_bytes(value.as_bytes()).unwrap(),
            );
        }
        let expected = reason(vector["reason"].as_str().unwrap());
        let outcomes = [
            webhook.verify_at(&body, &pairs, now).map(|_| ()),
            webhook.verify_at(&body, &hash, now).map(|_| ()),
            webhook.verify_at(&body, &header_map, now).map(|_| ()),
        ];
        for outcome in outcomes {
            match (expected, outcome) {
                (None, Ok(())) => {}
                (Some(reason), Err(error)) => assert_eq!(error.reason(), reason, "{id}: {error}"),
                (expected, outcome) => panic!("{id}: expected {expected:?}, got {outcome:?}"),
            }
        }
        // The string form of the body works too, when it is UTF-8.
        if let Some(text) = vector["body_utf8"].as_str() {
            assert_eq!(
                webhook.verify_at(text, &pairs, now).is_ok(),
                expected.is_none(),
                "{id}"
            );
        }
    }
}

#[test]
fn the_real_clock_rejects_old_vectors() {
    let vector = &vectors()[0];
    let body = base64::engine::general_purpose::STANDARD
        .decode(vector["body_base64"].as_str().unwrap())
        .unwrap();
    let headers: Vec<(String, String)> = vector["headers"]
        .as_object()
        .unwrap()
        .iter()
        .map(|(name, value)| (name.clone(), value.as_str().unwrap().to_owned()))
        .collect();
    let webhook = Webhook::new(vector["secret"].as_str().unwrap()).unwrap();
    let error = webhook.verify(&body, &headers).unwrap_err();
    assert_eq!(
        error.reason(),
        WebhookVerificationReason::TimestampOutOfTolerance
    );
    assert!(SystemTime::now() > UNIX_EPOCH + Duration::from_secs(vector["now"].as_u64().unwrap()));
}
