#!/usr/bin/env bash
# Regenerates (or, with --check, verifies) src/generated/ with the private
# lettermint/sdk-generator. Set LETTERMINT_SDK_GENERATOR to its checkout
# (default: ../sdk-generator next to this repository).
#
# Without the generator (CI, contributors without access), --check only
# verifies that every generated file carries the generator header with the
# spec commit and hashes, so that hand edits that drop the header are caught.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/src/generated"
files=(mod.rs support.rs types.rs operations.rs)
check=""
if [[ "${1:-}" == "--check" ]]; then
  check="--check"
elif [[ $# -gt 0 ]]; then
  echo "Usage: scripts/generate.sh [--check]" >&2
  exit 2
fi
generator="${LETTERMINT_SDK_GENERATOR:-$root/../sdk-generator}"

if [[ -d "$generator/lettermint_sdkgen" && -f "$generator/spec.next.lock.json" ]]; then
  cd "$generator"
  exec python3 -m lettermint_sdkgen emit rust --profile next --lock spec.next.lock.json --out "$out" $check
fi

if [[ -z "$check" ]]; then
  echo "The SDK generator was not found at $generator. Set LETTERMINT_SDK_GENERATOR to its checkout." >&2
  exit 1
fi

first=""
for name in "${files[@]}"; do
  file="$out/$name"
  if [[ ! -f "$file" ]]; then
    echo "src/generated/$name is missing. Regenerate it with the SDK generator." >&2
    exit 1
  fi
  header="$(head -n 5 "$file")"
  if ! grep -qx '// Generated by lettermint/sdk-generator — do not edit.' <<<"$(sed -n 1p <<<"$header")" ||
    ! grep -qE '^// Spec: lettermint/lettermint@[0-9a-f]{40}( \(.+\))?$' <<<"$(sed -n 2p <<<"$header")" ||
    ! grep -qE '^// sending-openapi\.json SHA-256: [0-9a-f]{64}$' <<<"$(sed -n 3p <<<"$header")" ||
    ! grep -qE '^// team-openapi\.json SHA-256: [0-9a-f]{64}$' <<<"$(sed -n 4p <<<"$header")" ||
    ! grep -qx '// Naming profile: next' <<<"$(sed -n 5p <<<"$header")"; then
    echo "src/generated/$name is missing the generator header. Regenerate it; do not edit it by hand." >&2
    exit 1
  fi
  if [[ -z "$first" ]]; then
    first="$header"
  elif [[ "$header" != "$first" ]]; then
    echo "The files in src/generated/ come from different specs. Regenerate them all." >&2
    exit 1
  fi
done
echo "SDK generator not found at $generator; checked the generated headers only."
sed -n 2p <<<"$first"
