// Code generated by Lettermint SDK generator; DO NOT EDIT.
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct EmailAttachment {
    pub filename: String,
    pub content: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum MessageStatus {
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "pending")]
    #[default]
    Pending,
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "suppressed")]
    Suppressed,
    #[serde(rename = "processed")]
    Processed,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "opened")]
    Opened,
    #[serde(rename = "clicked")]
    Clicked,
    #[serde(rename = "soft_bounced")]
    SoftBounced,
    #[serde(rename = "hard_bounced")]
    HardBounced,
    #[serde(rename = "spam_complaint")]
    SpamComplaint,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "policy_rejected")]
    PolicyRejected,
    #[serde(rename = "unsubscribed")]
    Unsubscribed,
    #[serde(rename = "canceled")]
    Canceled,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SendMailRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route: Option<String>,
    pub from: String,
    pub to: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cc: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bcc: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<Vec<String>>,
    pub subject: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::BTreeMap<String, String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<serde_json::Value>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<serde_json::Value>>,
}

pub type SendBatchMailRequest = Vec<SendMailRequest>;

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum TlsPolicy {
    #[serde(rename = "opportunistic")]
    #[default]
    Opportunistic,
    #[serde(rename = "enforced")]
    Enforced,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum AttachmentDelivery {
    #[serde(rename = "inline")]
    #[default]
    Inline,
    #[serde(rename = "url")]
    URL,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum BuiltInTeamRole {
    #[serde(rename = "owner")]
    #[default]
    Owner,
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "member")]
    Member,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct CursorPaginator {
    pub data: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    pub per_page: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum DkimMode {
    #[serde(rename = "legacy_txt")]
    #[default]
    LegacyTxt,
    #[serde(rename = "managed_cname")]
    ManagedCname,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum DnsRecordPurpose {
    #[serde(rename = "return_path")]
    #[default]
    ReturnPath,
    #[serde(rename = "dmarc")]
    Dmarc,
    #[serde(rename = "dkim_legacy")]
    DkimLegacy,
    #[serde(rename = "dkim_primary")]
    DkimPrimary,
    #[serde(rename = "dkim_secondary")]
    DkimSecondary,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum DnsRecordStatus {
    #[serde(rename = "active")]
    #[default]
    Active,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "pending")]
    Pending,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum DnsVerificationScope {
    #[serde(rename = "required")]
    #[default]
    Required,
    #[serde(rename = "recommended")]
    Recommended,
    #[serde(rename = "migration")]
    Migration,
    #[serde(rename = "deprecated")]
    Deprecated,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DomainData {
    pub id: String,
    pub domain: String,
    pub dkim_mode: DkimMode,
    pub rotation_ready: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_changed_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dns_records: Option<Vec<Box<DomainDnsRecordData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<serde_json::Value>>,
    pub created_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DomainDnsRecordData {
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: RecordType,
    pub hostname: String,
    pub fqdn: String,
    pub content: String,
    pub status: DnsRecordStatus,
    pub purpose: DnsRecordPurpose,
    pub verification_scope: DnsVerificationScope,
    pub required_for_verification: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_checked_at: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DomainListData {
    pub id: String,
    pub domain: String,
    pub status: DomainStatus,
    pub dkim_mode: DkimMode,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_changed_at: Option<String>,
    pub created_at: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum DomainStatus {
    #[serde(rename = "verified")]
    #[default]
    Verified,
    #[serde(rename = "partially_verified")]
    PartiallyVerified,
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "failed_verification")]
    FailedVerification,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum InitialRoutes {
    #[serde(rename = "both")]
    #[default]
    Both,
    #[serde(rename = "transactional")]
    Transactional,
    #[serde(rename = "broadcast")]
    Broadcast,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageAttachmentData {
    pub size: i64,
    pub filename: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
    pub content_type: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageData {
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: MessageType,
    pub status: MessageStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_changed_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    pub tags: Vec<serde_json::Value>,
    pub from_email: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to: Option<Vec<Box<MessageRecipientData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cc: Option<Vec<Box<MessageRecipientData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bcc: Option<Vec<Box<MessageRecipientData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<Box<MessageAttachmentData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::BTreeMap<String, String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spam_score: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spam_symbols: Option<Vec<Box<SpamSymbol>>>,
    pub route_id: String,
    pub created_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageEventData {
    pub message_id: String,
    pub event: MessageEventType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    pub tags: Vec<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub timestamp: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum MessageEventType {
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "rescheduled")]
    Rescheduled,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "released")]
    Released,
    #[serde(rename = "queued")]
    #[default]
    Queued,
    #[serde(rename = "processed")]
    Processed,
    #[serde(rename = "suppressed")]
    Suppressed,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "auto_replied")]
    AutoReplied,
    #[serde(rename = "soft_bounced")]
    SoftBounced,
    #[serde(rename = "hard_bounced")]
    HardBounced,
    #[serde(rename = "spam_complaint")]
    SpamComplaint,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "policy_rejected")]
    PolicyRejected,
    #[serde(rename = "unsubscribed")]
    Unsubscribed,
    #[serde(rename = "opened")]
    Opened,
    #[serde(rename = "clicked")]
    Clicked,
    #[serde(rename = "inbound_received")]
    InboundReceived,
    #[serde(rename = "inbound_queued")]
    InboundQueued,
    #[serde(rename = "inbound_spam_blocked")]
    InboundSpamBlocked,
    #[serde(rename = "inbound_processed")]
    InboundProcessed,
    #[serde(rename = "inbound_retry")]
    InboundRetry,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageListData {
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: MessageType,
    pub status: MessageStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spam_score: Option<f64>,
    pub from_email: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to: Option<Vec<Box<MessageRecipientData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cc: Option<Vec<Box<MessageRecipientData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bcc: Option<Vec<Box<MessageRecipientData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    pub tags: Vec<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_changed_at: Option<String>,
    pub created_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageRecipientData {
    pub email: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageStatsData {
    pub messages_transactional: i64,
    pub messages_broadcast: i64,
    pub messages_inbound: i64,
    pub deliverability: f64,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum MessageType {
    #[serde(rename = "inbound")]
    #[default]
    Inbound,
    #[serde(rename = "outbound")]
    Outbound,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum Plan {
    #[serde(rename = "free")]
    #[default]
    Free,
    #[serde(rename = "starter")]
    Starter,
    #[serde(rename = "growth")]
    Growth,
    #[serde(rename = "pro")]
    Pro,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum ProjectAccessScope {
    #[serde(rename = "all")]
    #[default]
    All,
    #[serde(rename = "selected")]
    Selected,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ProjectData {
    pub id: String,
    pub name: String,
    pub smtp_enabled: bool,
    pub redact_email_content: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_route_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_generated_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_last_used_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_last_used_ip: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<Box<RouteData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub routes_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domains: Option<Vec<Box<DomainData>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domains_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_28_days: Option<Box<MessageStatsData>>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ProjectListData {
    pub id: String,
    pub name: String,
    pub smtp_enabled: bool,
    pub routes_count: i64,
    pub domains_count: i64,
    pub last_28_days: Box<MessageStatsData>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum RbacConflictCode {
    #[serde(rename = "stale_resource")]
    #[default]
    StaleResource,
    #[serde(rename = "owner_protected")]
    OwnerProtected,
    #[serde(rename = "last_owner")]
    LastOwner,
    #[serde(rename = "built_in_role_immutable")]
    BuiltInRoleImmutable,
    #[serde(rename = "custom_role_requires_pro")]
    CustomRoleRequiresPro,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum RbacPermission {
    #[serde(rename = "team:manage")]
    #[default]
    TeamManage,
    #[serde(rename = "billing:manage")]
    BillingManage,
    #[serde(rename = "security:manage")]
    SecurityManage,
    #[serde(rename = "audit:read")]
    AuditRead,
    #[serde(rename = "support:manage")]
    SupportManage,
    #[serde(rename = "members:read")]
    MembersRead,
    #[serde(rename = "members:manage")]
    MembersManage,
    #[serde(rename = "roles:manage")]
    RolesManage,
    #[serde(rename = "team_tokens:read")]
    TeamTokensRead,
    #[serde(rename = "team_tokens:manage")]
    TeamTokensManage,
    #[serde(rename = "team_tokens:rotate")]
    TeamTokensRotate,
    #[serde(rename = "team_tokens:revoke")]
    TeamTokensRevoke,
    #[serde(rename = "projects:create")]
    ProjectsCreate,
    #[serde(rename = "team_suppressions:read")]
    TeamSuppressionsRead,
    #[serde(rename = "team_suppressions:add")]
    TeamSuppressionsAdd,
    #[serde(rename = "team_suppressions:remove")]
    TeamSuppressionsRemove,
    #[serde(rename = "projects:read")]
    ProjectsRead,
    #[serde(rename = "projects:manage")]
    ProjectsManage,
    #[serde(rename = "projects:delete")]
    ProjectsDelete,
    #[serde(rename = "routes:read")]
    RoutesRead,
    #[serde(rename = "routes:manage")]
    RoutesManage,
    #[serde(rename = "routes:delete")]
    RoutesDelete,
    #[serde(rename = "domains:read")]
    DomainsRead,
    #[serde(rename = "domains:manage")]
    DomainsManage,
    #[serde(rename = "domains:delete")]
    DomainsDelete,
    #[serde(rename = "project_tokens:read")]
    ProjectTokensRead,
    #[serde(rename = "project_tokens:manage")]
    ProjectTokensManage,
    #[serde(rename = "project_tokens:rotate")]
    ProjectTokensRotate,
    #[serde(rename = "project_tokens:revoke")]
    ProjectTokensRevoke,
    #[serde(rename = "webhooks:read")]
    WebhooksRead,
    #[serde(rename = "webhooks:manage")]
    WebhooksManage,
    #[serde(rename = "webhooks:delete")]
    WebhooksDelete,
    #[serde(rename = "webhooks:rotate_secret")]
    WebhooksRotateSecret,
    #[serde(rename = "stats:read")]
    StatsRead,
    #[serde(rename = "messages:read")]
    MessagesRead,
    #[serde(rename = "messages:read_content")]
    MessagesReadContent,
    #[serde(rename = "messages:send")]
    MessagesSend,
    #[serde(rename = "suppressions:read")]
    SuppressionsRead,
    #[serde(rename = "suppressions:add")]
    SuppressionsAdd,
    #[serde(rename = "suppressions:remove")]
    SuppressionsRemove,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum RecordType {
    #[serde(rename = "TXT")]
    #[default]
    TXT,
    #[serde(rename = "CNAME")]
    CNAME,
    #[serde(rename = "MX")]
    MX,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RouteData {
    pub id: String,
    pub project_id: String,
    pub slug: String,
    pub name: String,
    pub route_type: RouteType,
    pub is_default: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_domain_verified_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_spam_threshold: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachment_delivery: Option<AttachmentDelivery>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<ProjectData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhooks_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suppressed_recipients_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub statistics: Option<Vec<Box<RouteStatisticData>>>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RouteListData {
    pub id: String,
    pub slug: String,
    pub name: String,
    pub route_type: RouteType,
    pub is_default: bool,
    pub webhooks_count: i64,
    pub suppressed_recipients_count: i64,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RouteStatisticData {
    pub date: String,
    pub sent_count: i64,
    pub delivered_count: i64,
    pub opened_count: i64,
    pub clicked_count: i64,
    pub hard_bounce_count: i64,
    pub spam_complaint_count: i64,
    pub inbound_received_count: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observed_opened_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub human_opened_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub privacy_opened_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effective_opened_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_opened_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_clicked_count: Option<i64>,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum RouteType {
    #[serde(rename = "transactional")]
    #[default]
    Transactional,
    #[serde(rename = "broadcast")]
    Broadcast,
    #[serde(rename = "inbound")]
    Inbound,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SpamSymbol {
    pub name: String,
    pub score: f64,
    pub options: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StatsDailyData {
    pub date: String,
    pub sent: i64,
    pub delivered: i64,
    pub hard_bounced: i64,
    pub spam_complaints: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clicked: Option<i64>,
    pub inbound: Box<StatsInboundData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transactional: Option<Box<StatsTypeData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broadcast: Option<Box<StatsTypeData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observed_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub human_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub privacy_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effective_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_clicked: Option<i64>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StatsData {
    pub from: String,
    pub to: String,
    pub totals: Box<StatsTotalsData>,
    pub daily: Vec<Box<StatsDailyData>>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StatsInboundData {
    pub received: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StatsRequestData {
    pub from: String,
    pub to: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_machine: Option<bool>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StatsTotalsData {
    pub sent: i64,
    pub delivered: i64,
    pub hard_bounced: i64,
    pub spam_complaints: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clicked: Option<i64>,
    pub inbound: Box<StatsInboundData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transactional: Option<Box<StatsTypeData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub broadcast: Option<Box<StatsTypeData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observed_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub human_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub privacy_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effective_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_opened: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_clicked: Option<i64>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StatsTypeData {
    pub sent: i64,
    pub hard_bounced: i64,
    pub spam_complaints: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StoreDomainData {
    pub domain: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StoreProjectData {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub initial_routes: Option<InitialRoutes>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub short_token: Option<bool>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StoreRouteData {
    pub name: String,
    pub route_type: RouteType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StoreSuppressionData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub emails: Option<Vec<String>>,
    pub reason: SuppressionReason,
    pub scope: SuppressionScope,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct StoreWebhookData {
    pub route_id: String,
    pub name: String,
    pub url: String,
    pub events: Vec<WebhookEvent>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_machine_events: Option<bool>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SuppressedRecipientData {
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: SuppressionType,
    pub value: String,
    pub reason: SuppressionReason,
    pub scope: SuppressionScope,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_message: Option<Box<SuppressionSourceMessageData>>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum SuppressionReason {
    #[serde(rename = "spam_complaint")]
    #[default]
    SpamComplaint,
    #[serde(rename = "hard_bounce")]
    HardBounce,
    #[serde(rename = "unsubscribe")]
    Unsubscribe,
    #[serde(rename = "manual")]
    Manual,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum SuppressionScope {
    #[serde(rename = "global")]
    #[default]
    Global,
    #[serde(rename = "team")]
    Team,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "route")]
    Route,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SuppressionSourceMessageData {
    pub id: String,
    pub available: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum SuppressionType {
    #[serde(rename = "email")]
    #[default]
    Email,
    #[serde(rename = "domain")]
    Domain,
    #[serde(rename = "extension")]
    Extension,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamAddonData {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "type")]
    pub r#type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamData {
    pub id: String,
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: TeamType,
    pub plan: Plan,
    pub included_volume: i64,
    pub tier: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub addons: Option<Vec<Box<TeamAddonData>>>,
    pub created_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domains_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub projects_count: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub members_count: Option<i64>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamMemberData {
    pub id: String,
    pub name: String,
    pub email: String,
    pub role: serde_json::Value,
    pub project_access: Box<TeamMemberProjectAccessData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub joined_at: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamMemberProjectAccessData {
    pub scope: ProjectAccessScope,
    pub projects: Vec<serde_json::Value>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamRoleData {
    pub id: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_key: Option<BuiltInTeamRole>,
    pub permissions: Vec<RbacPermission>,
    pub assignable: bool,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum TeamType {
    #[serde(rename = "personal")]
    #[default]
    Personal,
    #[serde(rename = "business")]
    Business,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamUsageDetailData {
    pub current_period: Box<TeamUsagePeriodData>,
    pub historical_usage: Vec<Box<TeamUsagePeriodData>>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamUsagePeriodData {
    pub usage: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_incremented_at: Option<String>,
    pub period_start: String,
    pub period_end: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateDomainProjectsData {
    pub project_ids: Vec<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateProjectData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub smtp_enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redact_email_content: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_route_id: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateRouteData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<UpdateRouteSettingsData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_settings: Option<Box<UpdateRouteInboundSettingsData>>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateRouteInboundSettingsData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_spam_threshold: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachment_delivery: Option<AttachmentDelivery>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateRouteSettingsData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub track_opens: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub track_clicks: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generate_plaintext_fallback: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suppress_auto_responders: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suppress_disposable_recipients: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tls: Option<TlsPolicy>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disable_hosted_unsubscribe: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub redact_email_content: Option<bool>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateTeamData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateTeamMemberAssignmentData {
    pub role_id: String,
    pub project_access: serde_json::Value,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateWebhookData {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<WebhookEvent>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_machine_events: Option<bool>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookData {
    pub id: String,
    pub route_id: String,
    pub name: String,
    pub url: String,
    pub events: Vec<String>,
    pub enabled: bool,
    pub include_machine_events: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_called_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookDeliveryData {
    pub id: String,
    pub webhook_id: String,
    pub event_type: WebhookEvent,
    pub status: WebhookDeliveryStatus,
    pub attempt_number: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub http_status_code: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i64>,
    pub payload: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response_headers: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<String>,
    pub timestamp: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookDeliveryListData {
    pub id: String,
    pub webhook_id: String,
    pub event_type: WebhookEvent,
    pub status: WebhookDeliveryStatus,
    pub attempt_number: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub http_status_code: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<String>,
    pub created_at: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum WebhookDeliveryStatus {
    #[serde(rename = "pending")]
    #[default]
    Pending,
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "client_error")]
    ClientError,
    #[serde(rename = "server_error")]
    ServerError,
    #[serde(rename = "timeout")]
    Timeout,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub enum WebhookEvent {
    #[serde(rename = "message.created")]
    #[default]
    MessageCreated,
    #[serde(rename = "message.sent")]
    MessageSent,
    #[serde(rename = "message.delivered")]
    MessageDelivered,
    #[serde(rename = "message.auto_replied")]
    MessageAutoReplied,
    #[serde(rename = "message.hard_bounced")]
    MessageHardBounced,
    #[serde(rename = "message.soft_bounced")]
    MessageSoftBounced,
    #[serde(rename = "message.spam_complaint")]
    MessageSpamComplaint,
    #[serde(rename = "message.failed")]
    MessageFailed,
    #[serde(rename = "message.suppressed")]
    MessageSuppressed,
    #[serde(rename = "message.unsubscribed")]
    MessageUnsubscribed,
    #[serde(rename = "message.opened")]
    MessageOpened,
    #[serde(rename = "message.clicked")]
    MessageClicked,
    #[serde(rename = "message.inbound")]
    MessageInbound,
    #[serde(rename = "message.policy_rejected")]
    MessagePolicyRejected,
    #[serde(rename = "suppression.added")]
    SuppressionAdded,
    #[serde(rename = "suppression.removed")]
    SuppressionRemoved,
    #[serde(rename = "webhook.test")]
    WebhookTest,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookListData {
    pub id: String,
    pub route_id: String,
    pub name: String,
    pub url: String,
    pub events: Vec<WebhookEvent>,
    pub enabled: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_called_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SendMailResponse {
    pub message_id: String,
    pub status: MessageStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RescheduleMessageRequest {
    pub scheduled_at: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RescheduleMessageResponse {
    pub message_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<MessageStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
}

pub type SendBatchMailResponse = Vec<SendMailResponse>;

pub type PingResponse = i64;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DomainIndexResponse {
    pub data: Vec<Box<DomainListData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    pub per_page: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
}

pub type DomainStoreRequest = StoreDomainData;

pub type DomainStoreResponse = DomainData;

pub type DomainShowResponse = DomainData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DomainDestroyResponse {
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DomainVerifyDnsRecordsResponse {
    pub message: String,
    pub recommended_failed_records: Vec<serde_json::Value>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DomainVerifySpecificDnsRecordResponse {
    pub message: String,
}

pub type DomainUpdateProjectsRequest = UpdateDomainProjectsData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct DomainUpdateProjectsResponse {
    pub data: Box<DomainData>,
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct BlockedFileTypesResponse {
    pub extensions: Vec<String>,
    pub mime_types: Vec<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageIndexResponse {
    pub data: Vec<Box<MessageListData>>,
    pub links: Vec<String>,
    pub meta: serde_json::Value,
}

pub type MessageShowResponse = MessageData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct MessageEventsResponse {
    pub data: Vec<Box<MessageEventData>>,
    pub links: Vec<String>,
    pub meta: serde_json::Value,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ProjectIndexResponse {
    pub data: Vec<Box<ProjectListData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    pub per_page: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
}

pub type ProjectStoreRequest = StoreProjectData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ProjectStoreResponse {
    pub data: Box<ProjectData>,
    pub message: String,
    pub api_token: String,
}

pub type ProjectShowResponse = ProjectData;

pub type ProjectUpdateRequest = UpdateProjectData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ProjectUpdateResponse {
    pub data: Box<ProjectData>,
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ProjectDestroyResponse {
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct ProjectRotateTokenResponse {
    pub data: Box<ProjectData>,
    pub new_token: String,
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RouteIndexResponse {
    pub data: Vec<Box<RouteListData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    pub per_page: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
}

pub type RouteStoreRequest = StoreRouteData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RouteStoreResponse {
    pub data: Box<RouteData>,
    pub message: String,
}

pub type RouteShowResponse = RouteData;

pub type RouteUpdateRequest = UpdateRouteData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RouteUpdateResponse {
    pub data: Box<RouteData>,
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RouteDestroyResponse {
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct RouteVerifyInboundDomainResponse {
    pub data: serde_json::Value,
}

pub type StatsIndexResponse = StatsData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SuppressionIndexResponse {
    pub data: Vec<Box<SuppressedRecipientData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    pub per_page: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
}

pub type SuppressionStoreRequest = StoreSuppressionData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SuppressionStoreResponse {
    pub message: serde_json::Value,
    pub data: serde_json::Value,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct SuppressionDestroyResponse {
    pub success: bool,
    pub status: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
}

pub type TeamShowResponse = TeamData;

pub type TeamUpdateRequest = UpdateTeamData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamUpdateResponse {
    pub data: Box<TeamData>,
    pub message: String,
}

pub type TeamUsageResponse = TeamUsageDetailData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamRolesResponse {
    pub data: Vec<Box<TeamRoleData>>,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct TeamMembersResponse {
    pub data: Vec<Box<TeamMemberData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    pub per_page: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
}

pub type TeamMembersShowResponse = TeamMemberData;

pub type TeamMembersAssignmentUpdateRequest = UpdateTeamMemberAssignmentData;

pub type TeamMembersAssignmentUpdateResponse = TeamMemberData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookIndexResponse {
    pub data: Vec<Box<WebhookListData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    pub per_page: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
}

pub type WebhookStoreRequest = StoreWebhookData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookStoreResponse {
    pub data: Box<WebhookData>,
    pub message: String,
}

pub type WebhookShowResponse = WebhookData;

pub type WebhookUpdateRequest = UpdateWebhookData;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookUpdateResponse {
    pub data: Box<WebhookData>,
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookDestroyResponse {
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookTestResponse {
    pub message: String,
    pub delivery_id: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookRegenerateSecretResponse {
    pub data: Box<WebhookData>,
    pub message: String,
}

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct WebhookDeliveriesResponse {
    pub data: Vec<Box<WebhookDeliveryListData>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    pub per_page: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_cursor: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prev_page_url: Option<String>,
}

pub type WebhookShowDeliveryResponse = WebhookDeliveryData;
