name: Discord Notification

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Discord Release Webhook
        uses: lettermint/action-discord-releases@v1.0.1
        with:
          color: 'dea584'
          webhook_url: ${{ secrets.DISCORD_RELEASE_WEBHOOK_URL }}
          content: 'A new release for the Lettermint Rust SDK is now available! ||@Rust||'
